### ISSUE TITLE
Github State & Code State 如何部署使用

### ISSUE THREAD

**Issue by xieyuschen** [TankNee/TankNee#1]
请问这两块内容是如何生成的:)

**Comment by TankNee** [comment]
你可以直接看readme的源码
```markdnwon
### 📊 Github State

![Github State](https://github-readme-stats.vercel.app/api?username=TankNee&show_icons=true&hide_border=true)

### 📶 Code State

![Code Srare](https://github-readme-stats.vercel.app/api/top-langs/?username=TankNee&layout=compact&hide_border=true&title_color=a0a9af)
```
把url里的username改掉就行。
像这样：
### 📊 Github State

![Github State](https://github-readme-stats.vercel.app/api?username=Xieyuschen&show_icons=true&hide_border=true)

### 📶 Code State

![Code Srare](https://github-readme-stats.vercel.app/api/top-langs/?username=Xieyuschen&layout=compact&hide_border=true&title_color=a0a9af)
